/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class Semaforo1 extends javax.swing.JFrame {

    /**
     * Creates new form Semaforo1
     */
    public Semaforo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTexto1 = new javax.swing.JLabel();
        lbRojo = new javax.swing.JLabel();
        btCambiar = new javax.swing.JButton();
        lbImagen = new javax.swing.JLabel();
        lbAmarillo = new javax.swing.JLabel();
        lbVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbTexto1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        lbTexto1.setForeground(new java.awt.Color(255, 255, 255));
        lbTexto1.setText("Semaforo");

        lbRojo.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbRojo.setForeground(new java.awt.Color(255, 255, 255));
        lbRojo.setText("ROJO");

        btCambiar.setBackground(new java.awt.Color(204, 255, 204));
        btCambiar.setFont(new java.awt.Font("Wide Latin", 2, 18)); // NOI18N
        btCambiar.setText("Cambiar");
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/semI.jpg"))); // NOI18N
        lbImagen.setText("jLabel1");

        lbAmarillo.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbAmarillo.setForeground(new java.awt.Color(255, 255, 255));
        lbAmarillo.setText("AMARILLO");

        lbVerde.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbVerde.setForeground(new java.awt.Color(255, 255, 255));
        lbVerde.setText("VERDE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lbTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btCambiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbRojo)
                        .addGap(37, 37, 37)
                        .addComponent(lbAmarillo)
                        .addGap(33, 33, 33)
                        .addComponent(lbVerde))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btCambiar)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarActionPerformed
        // TODO add your handling code here:
    int numActivar = 1;

do {
    switch (numActivar) {
        case 1 -> {
            ImageIcon a = new ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Semaforo\\src\\Recursos\\semR.jpg");
            lbImagen.setIcon(a);
            lbRojo.setForeground(Color.RED);
            lbAmarillo.setForeground(Color.LIGHT_GRAY);
            lbVerde.setForeground(Color.LIGHT_GRAY);
            numActivar = 2;
        }
        case 2 -> {
            ImageIcon b = new ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Semaforo\\src\\Recursos\\semA.jpg");
            lbImagen.setIcon(b);
            lbAmarillo.setForeground(Color.YELLOW);
            lbRojo.setForeground(Color.LIGHT_GRAY);
            lbVerde.setForeground(Color.LIGHT_GRAY);
            numActivar = 3;
        }
        case 3 -> {
            ImageIcon c = new ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Semaforo\\src\\Recursos\\semV.jpg");
            lbImagen.setIcon(c);
            lbVerde.setForeground(Color.GREEN);
            lbRojo.setForeground(Color.LIGHT_GRAY);
            lbAmarillo.setForeground(Color.LIGHT_GRAY);
            numActivar = 1;
        }
        default -> {
        }
    }

    numActivar = (numActivar % 3) + 1;

    try {
        Thread.sleep(1000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }

} while (true);
        
    }//GEN-LAST:event_btCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //* Set the Nimbus look and feel *//
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Semaforo1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCambiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAmarillo;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbRojo;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbVerde;
    // End of variables declaration//GEN-END:variables
}
